ARG version
FROM almalinux:${version:-8}
ARG COURSE=Docker
ARG TRAINER=Avin
ENV Duration=120hrs
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER} and Duration is: ${Duration}"
CMD ["sleep", "200"]